site_name: Kubernetes Learnings
site_dir: site  # (optional) Output folder for the built site

theme:
  name: "material"
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      background: "#1A1A1A"
  language: en
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    # - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

nav:
  - Home: index.md
  - Chapter 04: Chapter-04/README.md

extra_css:
  - css/custom.css
